### ISSUE TITLE
proxy breaks redirecting during oauth

### ISSUE THREAD

**Issue by brandonmp** [zeit/micro-proxy#24]
I think this is what [this pr](https://github.com/zeit/micro-proxy/pull/17) is trying to address, but wanted to post the issue since pr seems inactive

I'm using `micro-proxy` to redirect to a local node server running passport w/ a LinkedIn Oauth2 strategy.  the relevant rule is:

```
...
{ "pathname": "/auth/**", "dest": "http://127.0.0.1:5555" },
...
```
However, when passport redirects to linked.com to authenticate, `micro-proxy` throws this error and the client never gets to linkedin:

```
FetchError: request to https://www.linkedin.com/oauth/v2/authorization?state={url params redacted} failed, reason: Hostname/IP does not match certificate's altnames: IP: 127.0.0.1 is not in the cert's list:
    at ClientRequest.<anonymous> (/mnt/c/Users/brand/code/my-project/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:165:20)
    at TLSSocket.socketErrorListener (_http_client.js:389:9)
    at TLSSocket.emit (events.js:160:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by andrewfinnell** [comment]
I suspect this may help you overcome this challenge, but you may still face the redirect one. https://stackoverflow.com/questions/33558076/cannot-use-ip-in-node-js-for-self-signed-certificate

The error you've posted appears to have to do with the SSL Certificate itself and not necessarily the OAuth issue. Are you using a Self-Signed CA on your back end?

**Comment by brandonmp** [comment]
> Are you using a Self-Signed CA on your back end?
Negative. My auth and nextjs server both deploy to `now.sh`, which I let handle all the SSL concerns.

The problem doesn't occur when I connect directly to my localhost auth server--only when connecting via `micro-proxy`.

**Comment by toddheslin** [comment]
I seem to be having the same issue in my setup. Here is what it looks like:

micro app => does some stuff but ultimately responds with a url redirect:
```
res.writeHead(301, {
	location: 'https://www.google.com'
})
```
This app is running on port 3000. When I hit it directly, it will redirect fine. The problem is when I'm using `micro-proxy`.

micro proxy => running on port 9000 with rules:
```
{
  "rules": [
    {
      "pathname": "/**",
      "dest": "http://localhost:3000"
    }
]}
```
When I hit the url now, the app running on `3000` will show me the 301 redirect, but I see an error on the proxy app along the lines of: `FetchError: request to https://www.google.com/ failed, reason: Hostname/IP doesn't match certificate's altnames: "Host: localhost. is not in the cert's altnames: DNS:www.google.com"`
